version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
         
     # build the application image
     - run: docker build -t $DOCKER_IMAGE:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push $DOCKER_IMAGE:$CIRCLE_BRANCH
     - run: ./.circleci/deploy.sh --cluster ecs-cluster --service renter-service --task renter $DOCKER_IMAGE:$CIRCLE_BRANCH